=== alternatex/Possom/war/src/webapp/dtds/AnalysisRules.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary indentification
    PUBLIC ID: -//sesam//Analysis//EN
    SYSTEM ID: http://sesam.no/dtds/AnalysisRules.dtd

    Author     : <a href="mailto:mick@wever.org">Michael Semb Wever</a>
    Version    : $Id: AnalysisRules.xml 42 2006-02-07 14:06:46Z magnuse $
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT rules (rule|predicate)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT predicate (not|none|all|any)*>
<!ATTLIST predicate
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT any (predicate)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT all (predicate)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT none (predicate,predicate+)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT not (predicate)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT rule (predicate*,score+)>
<!ATTLIST rule
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT score (#PCDATA)>
<!ATTLIST score
    predicate CDATA #IMPLIED
  >

=== alternatex/Possom/generic.sesam/war/src/main/conf/AnalysisRules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules SYSTEM "http://sesam.no/dtds/AnalysisRules.dtd">
<!--
    Copyright (2006) Schibsted SÃ¸k AS
    Document   : AnalysisRules.xml
    Created on : 25 January 2006, 13:21
    Author     : <a href="mailto:mick@wever.org">Michael Semb Wever</a>
    Version    : $Id: AnalysisRules.xml 10411 2007-08-30 13:04:55Z ssmiweve $
    Description:
        Purpose of the document follows.
-->

<rules evaluators="FAST,REGEX,JEP">


    <!-- Global predicates -->
    <predicate id="anyMagic">
        <any>
            <predicate id="BOOK_MAGIC"/>
            <predicate id="CATALOGUE_MAGIC"/>
            <predicate id="CULTURE_MAGIC"/>
            <predicate id="MOVIE_MAGIC"/>
            <predicate id="NEWS_MAGIC"/>
            <predicate id="OCEAN_MAGIC"/>
            <predicate id="PICTURE_MAGIC"/>
            <predicate id="RECEIPE_MAGIC"/>
            <predicate id="SKIINFO_MAGIC"/>
            <predicate id="STOCK_MAGIC"/>
            <predicate id="TV_MAGIC"/>
            <predicate id="WEATHER_MAGIC"/>
            <predicate id="WEBTV_MAGIC"/>
            <predicate id="WHITE_MAGIC"/>
            <predicate id="WIKIPEDIA_MAGIC"/>
            <predicate id="YELLOW_MAGIC"/>
        </any>
    </predicate>
    <predicate id="anyTrigger">
        <any>
            <predicate id="CATALOGUE_TRIGGER"/>
            <predicate id="NEWS_TRIGGER"/>
            <predicate id="PICTURE_TRIGGER"/>
            <predicate id="SKIINFO_TRIGGER"/>
            <predicate id="TV_TRIGGER"/>
            <predicate id="WEATHER_TRIGGER"/>
            <predicate id="WIKIPEDIA_TRIGGER"/>
        </any>
    </predicate>
    <predicate id="dropPredicates">
        <any>
            <predicate id="EXACT_CLASSIFIED_MAGIC"/>
            <predicate id="MATHPREDICATE"/>
            <predicate id="SITEPREFIX"/>
            <predicate id="TNS"/>
        </any>
    </predicate>
    <predicate id="geo">
        <any>
            <predicate id="GEOLOCAL"/>
            <predicate id="GEOGLOBAL"/>
        </any>
    </predicate>
    <predicate id="geoExact">
        <any>
            <predicate id="EXACT_GEOLOCAL"/>
            <predicate id="EXACT_GEOGLOBAL"/>
        </any>
    </predicate>
    <predicate id="exactFirstOrLast">
        <any>
            <predicate id="EXACT_FIRSTNAME"/>
            <predicate id="EXACT_LASTNAME"/>
        </any>
    </predicate>
    <predicate id="firstAndLastName">
        <all>
            <predicate id="FIRSTNAME"/>
            <predicate id="LASTNAME"/>
        </all>
    </predicate>
    <predicate id="firstOrLast">
        <any>
            <predicate id="FIRSTNAME"/>
            <predicate id="LASTNAME"/>
        </any>
    </predicate>
    <predicate id="firstOrLastAndGeo">
        <all>
            <predicate id="firstOrLast"/>
            <predicate id="geo"/>
        </all>
    </predicate>
    <predicate id="categoryOrKeyword">
        <any>
            <predicate id="CATEGORY"/>
            <predicate id="COMPANY_KEYWORD"/>
        </any>
    </predicate>
    <predicate id="bigCompany">
        <any>
            <predicate id="PRIOCOMPANYNAME"/>
            <predicate id="COMPANY_CHAIN"/>
        </any>
    </predicate>
    <predicate id="firstAndLastName-exactWiki-notCompany">
        <all>
            <predicate id="firstAndLastName"/>
            <predicate id="EXACT_WIKIPEDIA"/>
            <predicate>
                <any>
                    <predicate><not><predicate id="COMPANYSUFFIX"/></not></predicate>
                    <predicate><not><predicate id="TNS"/></not></predicate>
                </any>
            </predicate>
        </all>
    </predicate>
    <predicate id="englishWordsWithoutThisLanguage">
        <all>
            <predicate id="ENGLISHWORDS"/>
            <predicate>
                <none>
                    <predicate id="TNS"/>
                    <predicate id="EXACT_WIKIPEDIA"/>
                    <predicate id="geo"/>
                    <predicate id="COMPANY_KEYWORD"/>
                    <predicate id="CATEGORY"/>
                    <predicate id="firstOrLast"/>
                </none>
            </predicate>
        </all>
    </predicate>
    <predicate id="companyNotPerson">
        <all>
            <predicate id="COMPANYENRICHMENT"/>
            <predicate><not><predicate id="firstAndLastName"/></not></predicate>
        </all>
    </predicate>

    <predicate id="phoneOrOrgNr">
        <all>
            <predicate id="MATHPREDICATE"/>
            <predicate>
                <any>
                    <predicate id="PHONENUMBER"/>
                    <predicate id="ORGNR"/>
                </any>
            </predicate>
        </all>           
    </predicate>
    <predicate id="product">
        <any>
            <predicate id="PRODUCT_BICYCLE"/>
            <predicate id="PRODUCT_CAR"/>
            <predicate id="PRODUCT_CHILDREN"/>
            <predicate id="PRODUCT_CLOTHING"/>
            <predicate id="PRODUCT_CONSTRUCTION"/>
            <predicate id="PRODUCT_COSTUME"/>
            <predicate id="PRODUCT_ELECTRONIC"/>
            <predicate id="PRODUCT_FURNITURE"/>
            <predicate id="PRODUCT_GARDEN"/>
            <predicate id="PRODUCT_HOBBY"/>
            <predicate id="PRODUCT_HOUSEHOLD"/>
            <predicate id="PRODUCT_JEWELRY"/>
            <predicate id="PRODUCT_MOTOR"/>
            <predicate id="PRODUCT_MUSIC"/>
            <predicate id="PRODUCT_SHOE"/>
            <predicate id="PRODUCT_SPORT"/>
            <predicate id="PRODUCT_WATCH"/>
            <predicate id="PRODUCT_WEAPON"/>
        </any>
    </predicate>
    <predicate id="wikiAndCompany">
        <all>
            <predicate id="bigCompany"/>
            <predicate id="WIKIPEDIA"/>
        </all>
    </predicate>

    <predicate id="wikiAndWikiPrefix">
        <all>
            <predicate id="WIKIPEDIA_TRIGGER"/>
            <predicate id="WIKIPEDIA"/>
        </all>
    </predicate>
    
    <predicate id="exactWiki-notCompanyUnlessFullname">
        <all>
            <predicate id="EXACT_WIKIPEDIA"/>
            <predicate>
                <any>
                    <predicate>
                        <not>
                            <predicate id="EXACT_COMPANYENRICHMENT"/>
                        </not>
                    </predicate>
                    <predicate id="EXACT_FULLNAME"/>
                </any>
            </predicate>
        </all>
    </predicate>

    <!-- Rules -->
    
    
    <rule id="whitePages">

        <!-- private predicates -->
        <predicate id="customDropPredicates">
            <all>
                <predicate id="dropPredicates"/>
                <predicate>
                    <not><predicate id="FULLNAME"/></not>
                </predicate>
            </all>
        </predicate>

        <!-- Scoring -->
        <score predicate="CATALOGUE_MAGIC">1000</score>
        <score predicate="WHITE_MAGIC">1000</score>
        <score predicate="phoneOrOrgNr">500</score>
        <score predicate="CATALOGUE_TRIGGER">250</score>
        <score predicate="FULLNAME">10</score>
        <score predicate="anyMagic">-500</score>
        <score predicate="customDropPredicates">-500</score>
        <score predicate="exactFirstOrLast">-500</score>
        <score predicate="geoExact">-500</score>
    </rule>
    

    <rule id="yellowPages">

        <!-- private predicates -->
        <predicate id="firstAndLastNameAndCompanySuffix">
            <all>
                <predicate id="COMPANYSUFFIX"/>
                <predicate id="firstAndLastName"/>
            </all>
        </predicate>
        <predicate id="firstOrLastAndGeoNotCompany">
            <all>
                <predicate id="firstOrLastAndGeo"/>
                <predicate><not><predicate id="bigCompany"/></not></predicate>
                <predicate><not><predicate id="COMPANYSUFFIX"/></not></predicate>
                <predicate><not><predicate id="categoryOrKeyword"/></not></predicate>
            </all>
        </predicate>
        <predicate id="cataloguePrefixAndFirstOrLastNotCompany">
            <all>
                <predicate id="CATALOGUE_TRIGGER"/>
                <predicate id="firstOrLast"/>
                <predicate><not><predicate id="COMPANYSUFFIX"/></not></predicate>
            </all>
        </predicate>
        <predicate id="geoExactNotCompany">
            <all>
                <predicate id="geoExact"/>
                <predicate>
                    <not><predicate id="COMPANYENRICHMENT"/></not>
                </predicate>
            </all>
        </predicate>
        <predicate id="styleOrMaterial">
            <any>
                <predicate id="STYLE"/>
                <predicate id="MATERIAL"/>
            </any>
        </predicate>
        <predicate id="productAndGeo">
            <all>
                <predicate id="geo"/>
                <predicate id="product"/>
            </all>
        </predicate>
        <predicate id="categoryOrKeywordOrProduct">
            <any>
                <predicate id="categoryOrKeyword"/>
                <predicate id="product"/>
            </any>
        </predicate>

        <!-- Scoring postives -->
        <score predicate="CATALOGUE_MAGIC">1000</score>
        <score predicate="YELLOW_MAGIC">1000</score>
        <score predicate="phoneOrOrgNr">500</score>
        <score predicate="CATALOGUE_TRIGGER">250</score>
        <score predicate="companyNotPerson">200</score>
        <score predicate="firstAndLastNameAndCompanySuffix">200</score>
        <score predicate="PHONENUMBER">200</score>
        <score predicate="ORGNR">120</score>
        <score predicate="categoryOrKeywordOrProduct">100</score>
        <score predicate="bigCompany">30</score>
        <score predicate="TRADEMARK">30</score>
        <score predicate="productAndGeo">30</score>

        <!-- Scoring negatives -->
        <score predicate="styleOrMaterial">-100</score>
