=== alternatex/Possom/views.xsd
<?xml version='1.0'?>
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema' id='generic.sesam'>
    <xsd:element name='views' type='views'/>
    <xsd:complexType name='views'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='tab' type='tab'/>
        </xsd:choice>
        <xsd:attribute name='template-prefix'/>
    </xsd:complexType>
    <xsd:complexType name='tab'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='layout' type='layout'/>
			<xsd:element name='enrichment' type='enrichment'/>
			<xsd:element name='navigation' type='navigation'/>
			<xsd:element name='enrichment-placement' type='enrichment-placement'/>
	        <xsd:any minOccurs="0" processContents='lax'/>
        </xsd:choice>
        <xsd:attribute name='id'/>
        <xsd:attribute name='key'/>
        <xsd:attribute name='mode'/>
        <xsd:attribute name='inherit'/>
		<xsd:attribute name='rss-result-name'/>
		<xsd:attribute name='page-size'/>
		<xsd:attribute name='display-css'/>
		<xsd:attribute name='ad-on-top'/>
		<xsd:attribute name='css'/>
		<xsd:attribute name='ad-limit'/>
		<xsd:attribute name='javascript'/>
		<xsd:attribute name='execute-on-blank'/>
		<xsd:attribute name='parent-key'/>
    </xsd:complexType>
	<xsd:complexType name='layout'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='include' type='include'/>
			<xsd:element name='property' type='property'/>
        </xsd:choice>
        <xsd:attribute name='id'/>
        <xsd:attribute name='main'/>
        <xsd:attribute name='origin'/>
        <xsd:attribute name='front'/>
        <xsd:attribute name='content-type'/>
        <xsd:attribute name='expires-in-seconds' type="xsd:integer"/>
		<xsd:attribute name='display-css'/>
		<xsd:attribute name='css'/>
		<xsd:attribute name='javascript'/>
    </xsd:complexType>
	<xsd:complexType name='include'>
        <xsd:attribute name='key'/>
        <xsd:attribute name='template'/>
    </xsd:complexType>
	<xsd:complexType name='enrichment'>
        <xsd:attribute name='rule'/>
        <xsd:attribute name='threshold'/>
		<xsd:attribute name='weight'/>
		<xsd:attribute name='command'/>
    </xsd:complexType>
	   <xsd:complexType name='enrichment-placement'>
        <xsd:attribute name='id'/>
        <xsd:attribute name='max'/>
        <xsd:attribute name='threshold'/>
    </xsd:complexType>
	<xsd:complexType name='navigation'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='navigation' type='navigation'/>
			<xsd:element name='result-paging' type='result-paging'/>
			<xsd:element name='nav' type='nav'/>
			<xsd:element name='tree' type='tree'/>
			<xsd:element name='reset' type='reset'/>
			<xsd:element name='fast' type='fast'/>
        </xsd:choice>
        <xsd:attribute name='id'/>
		<xsd:attribute name='command-name'/>
		<xsd:attribute name='url-generator'/>
		<xsd:attribute name='prefix'/>
		<xsd:attribute name='tab'/>
		<xsd:attribute name='out'/>
		<xsd:attribute name='exclude-query'/>
		<xsd:attribute name='statistical-name'/>
    </xsd:complexType>
	<xsd:complexType name='result-paging'>
        <xsd:attribute name='id'/>
        <xsd:attribute name='command-name'/>
        <xsd:attribute name='page-size'/>
        <xsd:attribute name='multiple-page-size'/>
        <xsd:attribute name='number-of-pages'/>
		<xsd:attribute name='hitcount-source'/>
    </xsd:complexType>
	<xsd:complexType name='nav'>
		<xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='options' type='options'/>
			<xsd:any minOccurs="0" processContents='lax'/>
        </xsd:choice>
        <xsd:attribute name='id'/>
		<xsd:attribute name='field'/>
		<xsd:attribute name='command-name'/>
    </xsd:complexType>
	<xsd:complexType name='reset'>
        <xsd:attribute name='id'/>
    </xsd:complexType>
	<xsd:complexType name='tree'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='tree' type='tree'/>
        </xsd:choice>
        <xsd:attribute name='id'/>
        <xsd:attribute name='hide-parameter'/>
        <xsd:attribute name='name'/>
        <xsd:attribute name='parameters-to-keep'/>
		<xsd:attribute name='field'/>
    </xsd:complexType>
	<xsd:complexType name='options'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='config' type='config'/>
        </xsd:choice>
    </xsd:complexType>
	<xsd:complexType name='config'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='add' type='add'/>
			<xsd:element name='keep' type='keep'/>
        </xsd:choice>
    </xsd:complexType>
	<xsd:complexType name='add'>
        <xsd:attribute name='value'/>
        <xsd:attribute name='display-name'/>
        <xsd:attribute name='default-select'/>
        <xsd:attribute name='value-ref'/>
        <xsd:attribute name='default-select-value-ref'/>
		<xsd:attribute name='tab'/>
		<xsd:attribute name='command-name'/>
		<xsd:attribute name='use-hit-count'/>
		<xsd:anyAttribute/>
    </xsd:complexType>
	<xsd:complexType name='keep'>
        <xsd:attribute name='value'/>
        <xsd:attribute name='display-name'/>
    </xsd:complexType>
	<xsd:complexType name='fast'>
        <xsd:choice  minOccurs='0' maxOccurs='unbounded'>
            <xsd:element name='fast' type='fast'/>
			<xsd:element name='options' type='options'/>
			<xsd:element name='static-parameter' type='static-parameter'/>
        </xsd:choice>
		<xsd:attribute name='id'/>
		<xsd:attribute name='field'/>
		<xsd:attribute name='tab'/>
		<xsd:attribute name='out'/>
		<xsd:attribute name='command-name'/>
		<xsd:attribute name='maxsize'/>
		<xsd:attribute name='back-text'/>
		<xsd:attribute name='prefix'/>
		<xsd:attribute name='url-generator'/>
		<xsd:attribute name='auto-navigation'/>
		<xsd:attribute name='exclude-other-matches'/>
    </xsd:complexType>
	<xsd:complexType name='static-parameter'>
        <xsd:attribute name='value'/>
        <xsd:attribute name='name'/>
    </xsd:complexType>
	<xsd:complexType name='property'>
        <xsd:attribute name='key'/>
        <xsd:attribute name='value'/>
    </xsd:complexType>
</xsd:schema>

=== alternatex/Possom/generic.sesam/sesam.com/war/src/main/conf/views.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (2008) Schibsted ASA
 *   This file is part of SESAT.
 *
 *   SESAT is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   SESAT is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with SESAT.  If not, see <http://www.gnu.org/licenses/>.
 *
    Document   : views.xml
    Created on : 4 April 2006, 16:25
    Author     : mick
    Description:
        Purpose of the document follows. -->

<views xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../views.xsd">
    <!-- Override default to show its css -->
    <tab id="default" display-css="true" inherit="default"/>
    <!-- Our base sesam.com view -->
    <tab id="default-sesam-com" inherit="default"/>
    <!-- The one vertical we have. -->
    <tab id="international" inherit="default-sesam-com"
            key="g"
            mode="international" 
            page-size="10"
            rss-result-name="globalSearch">
        <navigation>
            <navigation id="offset">
              <result-paging id="offset" command-name="globalSearch" page-size="10" number-of-pages="10" hitcount-source="totalhits"/>
            </navigation>
        </navigation>
        <layout main="sesam.com/main.jsp" front="sesam.com/index.jsp">
            <include key="head-element" template="sesam.com/head.jsp"/>
            <include key="head-element-extra" template="sesam.com/mwsuggest.jsp"/>
            <include key="top-col-one" template="sesam.com/searchbar-top.jsp"/>
            <include key="main-col-three" template="sesam.com/globalSearch.jsp"/>
            <include key="bottom-col-one" template="sesam.com/offsetPager.jsp"/>
            <include key="bottom-col-three" template="sesam.com/footer.jsp"/>
            <include key="bottom-col-two" template="sesam.com/searchbar-bottom.jsp"/>
            <include key="offsetPagerLogo" template=""/>          
            <include key="no-hits" template="sesam.com/no-hits.jsp"/>   
        </layout>
    </tab>
</views>
